name: rehabox
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  build_runner: ^2.4.8
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.12
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  http: ^1.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  matcher: ^0.12.16
  mockito: ^5.4.4
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  test: ^1.24.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
